---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sinker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sinker
subjects:
  - kind: ServiceAccount
    name: sinker
    namespace: sinker
